version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    ports:
      - "80:80"
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on: 
      - "db"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DB_SERVER=${DB_SERVER}
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
